apiVersion: v1
kind: Template
metadata:
  name: mem-migrator
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "mem-migrator" 
  spec:
    runPolicy: "Serial" 
    source: 
      git:
        uri: "https://github.com/num46664/mem-migrator"
    strategy: 
      dockerStrategy:
        from:
          kind: "DockerImage"
          name: "python:3.7"
    output: 
      to:
        kind: "ImageStreamTag"
        name: "mem-migrator:latest"
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      build: mem-migrator
    name: mem-migrator
    namespace: mem-mmt-tools